#!/usr/bin/perl
# wordnet-to-datalog.pl - Convert WordNet Prolog to Datalog Facts
# Outputs: Prolog/Datalog style with pairwise (channel . value) notation
# This format is parseable by the Tetragrammatron meta-circular Lisp

use strict;
use warnings;

my $prolog_dir = $ARGV[0] || '/home/main/Downloads/WNprolog-3.0/prolog';

die "Prolog directory not found: $prolog_dir\n" unless -d $prolog_dir;

print <<"HEADER";
%% ============================================================
%% wordnet.dl - WordNet 3.0 as Datalog Facts
%% Generated by wordnet-to-datalog.pl
%% Source: $prolog_dir
%% Format: Prolog/Datalog with pairwise (car . cdr) notation
%% ============================================================

%% Constitutional Constants
:- const constitutional_c = 16#1D.
:- const channel_fs = 16#1C.
:- const channel_gs = 16#1D.
:- const channel_rs = 16#1E.
:- const channel_us = 16#1F.

%% ============================================================
%% FACTS: synset(synset_id, lemma, pos, sense_count)
%% ============================================================

HEADER

my %synsets;
my %relations;

# Parse wn_s.pl - synsets
print "%% Loading synsets...\n";
my $s_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_s.pl")) {
    while (<$fh>) {
        if (/s\((\d+),(\d+),'([^']+)',([nvasr]),(\d+),(\d+)\)/) {
            my ($synset_id, $sense, $lemma, $pos, $cnt, $hr_cnt) = 
                ($1, $2, $3, $4, $5, $6);
            
            $synsets{$synset_id} = {
                lemma => $lemma,
                pos => $pos,
                sense_count => $cnt,
                hr_count => $hr_cnt
            };
            $s_count++;
        }
    }
    close($fh);
}
print "%% Total synsets: $s_count\n\n";

# Output synsets as Datalog facts (limited for demo)
print "%% Synset Facts (sample)\n";
my @synset_ids = sort { $a <=> $b } keys %synsets;
my $limit = @synset_ids > 100 ? 100 : @synset_ids;
for (my $i = 0; $i < $limit; $i++) {
    my $id = $synset_ids[$i];
    my $s = $synsets{$id};
    my $lemma = $s->{lemma};
    $lemma =~ s/'/\\'/g;
    print "synset($id, '$lemma', $s->{pos}, $s->{sense_count}).\n";
}
print "%% ... and " . (@synset_ids - $limit) . " more synsets\n\n";

# Parse hypernyms
print "%% ============================================================\n";
print "%% FACTS: hypernym(child, parent)\n%% ============================================================\n\n";

my $hyp_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_hyp.pl")) {
    while (<$fh>) {
        if (/hyp\((\d+),(\d+)\)/) {
            push @{$relations{hypernym}}, [$1, $2];
            $hyp_count++;
        }
    }
    close($fh);
}
print "%% Total hypernyms: $hyp_count\n\n";

# Output hypernyms as Datalog facts
print "%% Hypernym Facts\n";
$limit = @{$relations{hypernym}} > 100 ? 100 : @{$relations{hypernym}};
for (my $i = 0; $i < $limit; $i++) {
    my ($child, $parent) = @{$relations{hypernym}[$i]};
    print "hypernym($child, $parent).\n";
}
print "%% ... and " . (@{$relations{hypernym}} - $limit) . " more hypernyms\n\n";

# Parse antonyms
print "%% ============================================================\n";
print "%% FACTS: antonym(source, target)\n%% ============================================================\n\n";

my $ant_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_ant.pl")) {
    while (<$fh>) {
        if (/ant\((\d+),(\d+),(\d+)\)/) {
            push @{$relations{antonym}}, [$1, $2, $3];
            $ant_count++;
        }
    }
    close($fh);
}
print "%% Total antonyms: $ant_count\n\n";

if ($ant_count > 0) {
    print "%% Antonym Facts\n";
    $limit = @{$relations{antonym}} > 50 ? 50 : @{$relations{antonym}};
    for (my $i = 0; $i < $limit; $i++) {
        my ($src, $tgt, $type) = @{$relations{antonym}[$i]};
        print "antonym($src, $tgt).\n";
    }
    print "%% ... and " . (@{$relations{antonym}} - $limit) . " more antonyms\n\n";
}

print <<"RULES";
%% ============================================================
%% RULES: Derived Relations
%% ============================================================

%% Ancestor traversal (transitive closure of hypernym)
ancestor(X, Y) :- hypernym(X, Y).
ancestor(X, Z) :- hypernym(X, Y), ancestor(Y, Z).

%% Path from entity to root
path_to_entity(X, [X]) :- synset(X, _, _, _), not hypernym(X, _).
path_to_entity(X, [X|P]) :- hypernym(X, Y), path_to_entity(Y, P).

%% Depth in hierarchy
depth(X, 0) :- synset(X, _, _, _), not hypernym(X, _).
depth(X, D) :- hypernym(X, Y), depth(Y, D1), D is D1 + 1.

%% ============================================================
%% PAIRWISE NOTATION: (channel . value) encoding
%% ============================================================

%% Convert synset_id to pairwise (car . cdr)
%% channel: FS=28, GS=29, RS=30, US=31 (ASCII separators)
synset_pair(S, (fs . C)) :- 
    S > 100000000, C is S mod 100000000.
synset_pair(S, (gs . C)) :- 
    S > 1000000, S =< 100000000, C is S.
synset_pair(S, (rs . C)) :- 
    S > 10000, S =< 1000000, C is S.
synset_pair(S, (us . C)) :- 
    S =< 10000, C is S.

%% Semantic ID: K(synset_id, C) where C = 0x1D
sid(S, SID) :- 
    SID is xor(xor(rotl(S, 1), rotl(S, 3)), rotr(S, 2)) xor 16#1D.

rotl(X, N) :- N1 is N mod 32, (X << N1) \/ (X >> (32 - N1)).
rotr(X, N) :- N1 is N mod 32, (X >> N1) \/ (X << (32 - N1)).

%% ============================================================
%% QUERIES (can be evaluated by Tetragrammatron Lisp)
%% ============================================================

%% Find all hypernyms of a synset
query_hypernyms(Synset, Parents) :- 
    findall(P, hypernym(Synset, P), Parents).

%% Find path from concept to root entity
query_path(Synset, Path) :- 
    path_to_entity(Synset, Path).

%% Calculate depth in taxonomy
query_depth(Synset, Depth) :- 
    depth(Synset, Depth).

%% Get SID for synset
query_sid(Synset, SID) :- 
    sid(Synset, SID).

%% End of wordnet.dl
RULES
