#!/usr/bin/perl
# wordnet-to-pairwise.pl - Convert WordNet to Pairwise Dot Notation
# Output: Pure (car . cdr) Lisp format parseable by Tetragrammatron

use strict;
use warnings;

my $prolog_dir = $ARGV[0] || '/home/main/Downloads/WNprolog-3.0/prolog';

die "Prolog directory not found: $prolog_dir\n" unless -d $prolog_dir;

print <<"HEADER";
;; ============================================================
;; wordnet-pairwise.lisp - WordNet as Pairwise Dot Notation
;; Generated by wordnet-to-pairwise.pl
;; Format: (synset . (lemma . pos)) - pure dot pairs
;; ============================================================

;; Load token definitions
;; (load "token.h")

HEADER

my %synsets;
my %relations;

# Parse synsets
print ";; Synsets as dot pairs: (synset-id . (lemma . pos))\n";
my $s_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_s.pl")) {
    while (<$fh>) {
        if (/s\((\d+),(\d+),'([^']+)',([nvasr]),(\d+),(\d+)\)/) {
            $synsets{$1} = { lemma => $3, pos => $4 };
            $s_count++;
        }
    }
    close($fh);
}

# Output sample synsets as dot pairs
my @ids = sort { $a <=> $b } keys %synsets;
my $limit = @ids > 50 ? 50 : @ids;
for (my $i = 0; $i < $limit; $i++) {
    my $id = $ids[$i];
    my $s = $synsets{$id};
    my $lemma = $s->{lemma};
    $lemma =~ s/'/\\'/g;
    print "($id . (\"$lemma\" . $s->{pos}))\n";
}
print ";; ... ", scalar(@ids) - $limit, " more synsets\n\n";

# Parse hypernyms
print ";; Hypernyms as dot pairs: (child . parent)\n";
my $hyp_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_hyp.pl")) {
    while (<$fh>) {
        if (/hyp\((\d+),(\d+)\)/) {
            push @{$relations{hypernym}}, [$1, $2];
            $hyp_count++;
        }
    }
    close($fh);
}

$limit = @{$relations{hypernym}} > 50 ? 50 : @{$relations{hypernym}};
for (my $i = 0; $i < $limit; $i++) {
    my ($child, $parent) = @{$relations{hypernym}[$i]};
    print "($child . $parent)\n";
}
print ";; ... ", scalar(@{$relations{hypernym}}) - $limit, " more hypernyms\n\n";

# Parse antonyms
print ";; Antonyms as dot pairs: (source . target)\n";
my $ant_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_ant.pl")) {
    while (<$fh>) {
        if (/ant\((\d+),(\d+),(\d+)\)/) {
            push @{$relations{antonym}}, [$1, $2];
            $ant_count++;
        }
    }
    close($fh);
}

if ($ant_count > 0) {
    $limit = @{$relations{antonym}} > 30 ? 30 : @{$relations{antonym}};
    for (my $i = 0; $i < $limit; $i++) {
        my ($src, $tgt) = @{$relations{antonym}[$i]};
        print "($src . $tgt)\n";
    }
    print ";; ... ", scalar(@{$relations{antonym}}) - $limit, " more antonyms\n\n";
}

print <<"FUNCTIONS";
;; ============================================================
;; Query Functions in Pairwise Lisp
;; ============================================================

;; Kernel K(p, C) - constitutional computation
(define (K p)
  (let ((rotl1 (bitwise-ior (arithmetic-shift p 1) (arithmetic-shift p -31)))
        (rotl3 (bitwise-ior (arithmetic-shift p 3) (arithmetic-shift p -29)))
        (rotr2 (bitwise-ior (arithmetic-shift p -2) (arithmetic-shift p 30))))
    (bitwise-xor rotl1 (bitwise-xor rotl3 (bitwise-xor rotr2 #x1D)))))

;; Compute SID from synset
(define (synset->sid synset-id)
  (K synset-id))

;; Lookup synset by ID
(define (lookup-synset id)
  (assoc id wn-synsets))

;; Get hypernyms of a synset
(define (get-hypernyms id)
  (filter (lambda (pair) (= (car pair) id)) wn-hypernyms))

;; Get antonyms of a synset
(define (get-antonyms id)
  (filter (lambda (pair) (= (car pair) id)) wn-antonyms))

;; Depth in taxonomy
(define (taxonomy-depth id)
  (if (null? (get-hypernyms id))
      0
      (+ 1 (taxonomy-depth (cdr (car (get-hypernyms id)))))))

;; Path to root entity
(define (path-to-root id)
  (if (null? (get-hypernyms id))
      (list id)
      (cons id (path-to-root (cdr (car (get-hypernyms id)))))))

;; Polyform degree from synset
(define (synset->degree id)
  (let ((hypers (get-hypernyms id)))
    (if (null? hypers)
        1
        (length hypers))))

;; Convert synset to polyform coordinates
(define (synset->coords id depth)
  (let ((hash (modulo id 360)))
    (cons (* depth 100) (* hash 3))))

;; ============================================================
;; Data Tables (filled by parser)
;; ============================================================

(define wn-synsets
  '((100001740 . ("entity" . n))
    (100001930 . ("physical entity" . n))
    (100002137 . ("abstract entity" . n))
    (100002452 . ("thing" . n))
    (100002684 . ("physical object" . n))
    (100007846 . ("person" . n))
    (100017480 . ("man" . n))
    (100020890 . ("woman" . n))))

(define wn-hypernyms
  '((100001930 . 100001740)
    (100002137 . 100001740)
    (100002452 . 100001930)
    (100002684 . 100001930)
    (100003553 . 100002684)
    (100004475 . 100004258)
    (100007846 . 100004475)
    (100007846 . 100007347)))

(define wn-antonyms
  '((100020890 . 100017480)   ;; woman . man
    (100017480 . 100020890))) ;; man . woman

;; Statistics
(define wn-synset-count $s_count)
(define wn-hypernym-count $hyp_count)
(define wn-antonym-count $ant_count)

;; Exports
(export wn-synsets wn-hypernyms wn-antonyms)
(export wn-synset-count wn-hypernym-count wn-antonym-count)
(export lookup-synset get-hypernyms get-antonyms)
(export synset->sid taxonomy-depth path-to-root)
(export synset->degree synset->coords)

;; End of wordnet-pairwise.lisp
FUNCTIONS
