#!/usr/bin/perl
# wordnet-to-lisp.pl - Convert WordNet Prolog to Pairwise Lisp
# Usage: perl wordnet-to-lisp.pl [prolog_dir] > wordnet.lisp

use strict;
use warnings;
use File::Basename;

my $prolog_dir = $ARGV[0] || '/home/main/Downloads/WNprolog-3.0/prolog';

die "Prolog directory not found: $prolog_dir\n" unless -d $prolog_dir;

print <<"HEADER";
;; ============================================================
;; wordnet.lisp - WordNet 3.0 as Pairwise Lisp
;; Generated by wordnet-to-lisp.pl
;; Source: $prolog_dir
;; ============================================================

;;; Constitutional Constants
(define CONSTITUTIONAL-C #x1D)
(define CHANNEL-FS #x1C)
(define CHANNEL-GS #x1D)
(define CHANNEL-RS #x1E)
(define CHANNEL-US #x1F)

;;; Synset Hash (synset-id -> properties)
(define wn-synsets (make-hash-table))

HEADER

my %synsets;
my %relations;

# Parse wn_s.pl - synsets
print ";;; Loading synsets...\n";
my $s_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_s.pl")) {
    while (<$fh>) {
        if (/s\((\d+),(\d+),'([^']+)',([nvasr]),(\d+),(\d+)\)/) {
            my ($synset_id, $sense, $lemma, $pos, $cnt, $hr_cnt) = 
                ($1, $2, $3, $4, $5, $6);
            
            $synsets{$synset_id} = {
                lemma => $lemma,
                pos => $pos,
                sense_count => $cnt,
                hr_count => $hr_cnt
            };
            $s_count++;
        }
    }
    close($fh);
}
print "(define wn-synset-count $s_count)\n\n";

# Parse wn_hyp.pl - hypernyms
print ";;; Loading hypernyms...\n";
my $hyp_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_hyp.pl")) {
    while (<$fh>) {
        if (/hyp\((\d+),(\d+)\)/) {
            push @{$relations{hypernym}}, [$1, $2];
            $hyp_count++;
        }
    }
    close($fh);
}
print "(define wn-hypernym-count $hyp_count)\n\n";

# Parse wn_ant.pl - antonyms
my $ant_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_ant.pl")) {
    while (<$fh>) {
        if (/ant\((\d+),(\d+),(\d+)\)/) {
            push @{$relations{antonym}}, [$1, $2, $3];
            $ant_count++;
        }
    }
    close($fh);
}
print "(define wn-antonym-count $ant_count)\n\n";

# Parse wn_mer.pl - meronyms (part-of)
my $mer_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_mm.pl")) {
    while (<$fh>) {
        if (/mer\((\d+),(\d+),(\d+)\)/) {
            push @{$relations{meronym}}, [$1, $2, $3];
            $mer_count++;
        }
    }
    close($fh);
}
print "(define wn-meronym-count $mer_count)\n\n";

# Parse wn_der.pl - derivationally related
my $der_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_der.pl")) {
    while (<$fh>) {
        if (/der\((\d+),(\d+),(\d+)\)/) {
            push @{$relations{derived}}, [$1, $2, $3];
            $der_count++;
        }
    }
    close($fh);
}
print "(define wn-derived-count $der_count)\n\n";

# Parse wn_sim.pl - similar to
my $sim_count = 0;
if (open(my $fh, '<', "$prolog_dir/wn_sim.pl")) {
    while (<$fh>) {
        if (/sim\((\d+),(\d+),(\d+)\)/) {
            push @{$relations{similar}}, [$1, $2, $3];
            $sim_count++;
        }
    }
    close($fh);
}
print "(define wn-similar-count $sim_count)\n\n";

print <<"RELATIONS";
;;; ============================================================
;;; Relation Graphs as Pairwise Lists
;;; ============================================================

RELATIONS

# Hypernyms as (child . parent) pairs
print ";;; Hypernym hierarchy: (hypernym child parent)\n";
my $limit = @{$relations{hypernym}} > 50 ? 50 : @{$relations{hypernym}};
for (my $i = 0; $i < $limit; $i++) {
    my ($child, $parent) = @{$relations{hypernym}[$i]};
    print "(hypernym $child $parent)\n";
}
if (@{$relations{hypernym}} > 50) {
    print ";; ... and @{$relations{hypernym}} more hypernyms\n";
}
print "\n";

# Antonyms as (antonym source target)
print ";;; Antonym relations: (antonym source target)\n";
$limit = @{$relations{antonym}} > 30 ? 30 : @{$relations{antonym}};
for (my $i = 0; $i < $limit; $i++) {
    my ($src, $tgt, $type) = @{$relations{antonym}[$i]};
    print "(antonym $src $tgt)\n";
}
if (@{$relations{antonym}} > 30) {
    print ";; ... and @{$relations{antonym}} more antonyms\n";
}
print "\n";

print <<"FUNCTIONS";
;;; ============================================================
;;; Constitutional Kernel Queries
;;; ============================================================

(define (lookup-synset id)
  (hash-ref wn-synsets id))

(define (get-hypernyms synset-id)
  (filter (lambda (r) (= (car r) synset-id))
          wn-hypernyms))

(define (get-antonyms synset-id)
  (filter (lambda (r) (= (car r) synset-id))
          wn-antonyms))

;;; Polyform generation from synset
(define (synset->polyform synset-id)
  (let* ((syn (lookup-synset synset-id))
         (degree (if syn (cdr (assoc 'hr_count syn)) 0)))
    (cons degree synset-id)))

;;; Coordinate mapping for visual knowledge graph
(define (synset->coordinates synset-id depth)
  (let* ((hash (modulo synset-id 360))
         (x (* depth 100))
         (y (* hash 2)))
    (cons x y)))

;;; ============================================================
;;; Exports
;;; ============================================================

(define wn-hypernyms
  '((100001930 . 100001740)
    (100002137 . 100001740)
    (100002452 . 100001930)
    (100002684 . 100001930)))

(define wn-antonyms
  '((100001930 . 100001740)
    (100002137 . 100001740)))

(export wn-synset-count wn-hypernym-count wn-antonym-count)
(export wn-synsets wn-hypernyms wn-antonyms)
(export lookup-synset get-hypernyms get-antonyms)
(export synset->polyform synset->coordinates)

;;; End of wordnet.lisp
FUNCTIONS
